### ISSUE TITLE
README.md crypto-util/sign-util path error

### ISSUE THREAD

**Issue by ivy-dong** [arxanchain/py-common#4]
when I use Wallet register API, shows error:
`sh: /usr/local/lib/python2.7/site-packages/py_common-1.5.0-py2.7.egg/cryption/./utils/crypto-util: No such file or directory`
actually I hava already  copy crypto-util/sign-util into directory` py-common/cryption/utils` as README.md said.
pls update README.md.

**Comment by Honghaohan2013** [comment]
fixed.
